<?php
/**
 * Created by PhpStorm.
 * User: James
 * Date: 2018/6/10
 * Time: 18:25
 */

namespace app\controllers;
use app\controllers\formbeans\CreateNewPollFormBeanFactory;
use comphp\base\Controller;
use app\models\BoardModel;

include(APP_PATH . 'app/controllers/formbeans/'.'CreateNewPollFormBean.php');

define('NEWPOLL_ACTION_INIT', "init" );

define('NEWPOLL_ACTION_ADD', "add" );

class CreateNewPollController extends Controller
{
    private $formBean;

    private $boardModel;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->formBean = CreateNewPollFormBeanFactory::create();

        $this->boardModel = new BoardModel();

        if($this->_actionName == NEWPOLL_ACTION_INIT){

            $this->initViewParasFunction();

        }elseif ($this->_actionName == NEWPOLL_ACTION_ADD){

            $this->addFunction();

        }

        $this->assign('boardsInfoArray', $this->formBean->getBoards() );

        $this->render();

    }

    private function initViewParasFunction(){


        $boardInfos = $this->boardModel->searchAllBoard();

        if ( $boardInfos  && $boardInfos->size()>0 ){

            $boardArray = array();

            $rows = $boardInfos->fetchAll();

            foreach ($rows as $key=>$aRow){

                $boardKey = $aRow['boardID'];
                $boardValue = $aRow['boardName'];

                $boardArrayTmp = array(

                    $boardKey => $boardValue

                );

                //var_dump($boardArrayTmp);

                $boardArray = array_merge($boardArray,$boardArrayTmp);

            }


            //var_dump($boardArray);

            $this->formBean->setBoards($boardArray);

        }

    }

    private function addFunction(){

    }
}