<?php
/**
 * Created by PhpStorm.
 * User: yac0105
 * Date: 12/06/2018
 * Time: 4:18 PM
 */

namespace app\controllers;


use comphp\base\Controller;
use app\controllers\formbeans\PollRstFormBean;
use app\controllers\formbeans\PollRstFormBeanFactory;
use app\models\modelInterface\PollModelService;
use app\models\modelInterface\PollModelServiceImpl;

include(APP_PATH . 'app/controllers/formbeans/'.'PollRstFormBean.php');

CONST POLL_RST_INIT = "init";

class PollRstController extends Controller
{

    private $formBean;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->formBean = PollRstFormBeanFactory::create();

        if(isset($_SESSION['PollId'])){
            $pollID = $_SESSION['PollId'];
        }

        if(POLL_RST_INIT == $this->_actionName){
            if(!empty($pollID)){


                $this->displayPollDetail(new PollModelServiceImpl());


            }else{
                throw new \Exception("Cannot get PollID!");
            }
        }





        $this->render();
    }

    private function displayPollDetail(PollModelService $pollModelService){



    }
}

