<?php
/**
 * Created by PhpStorm.
 * User: yac0105
 * Date: 5/06/2018
 * Time: 12:57 PM
 */
namespace app\controllers;

use comphp\base\Controller;

class PostController extends Controller
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->render();
    }


}