<?php
/**
 * Created by PhpStorm.
 * User: yac0105
 * Date: 5/06/2018
 * Time: 12:57 PM
 */
namespace app\controllers;

use comphp\base\Controller;
use app\models\modelInterface\PollModelService;
use app\models\modelInterface\PollModelServiceImpl;

const POST_QUERY_INIT = 'query';

class PostController extends Controller
{

    private $pollRstBeanCollection;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        //$action = $this->_actionName;

        //var_dump($action) ;
        //echo strrpos($action,"board");

        $boardId = 1;

        if(strrpos($this->_actionName,"board")>0){

            //echo 'haha';

            $begin = strrpos($this->_actionName,"_") + 1;

            $boardId = intval(substr($this->_actionName,$begin));
        }

        $this->displayAllPost(new PollModelServiceImpl(), $boardId);


        $this->assign('pollRstBeanCollection',$this->pollRstBeanCollection);

        $this->render();
    }

    public function displayAllPost(PollModelService $pollModelService, $boardId){

        //var_dump($boardId);

        $rst = $pollModelService->searchPollByBoardID($boardId);

        //var_dump($rst);

        if($rst->isSuccess()){

            $this->pollRstBeanCollection = $rst->getResult();

        }else{

            $this->_formbean->setWarning('Fail to get polls');

        }



    }

}